### ISSUE TITLE
Graph fix in Statistics & Bar Charts

### ISSUE THREAD

**Issue by mattcristal** [tracking-exposed/pornhub.tracking.exposed#10]
![newcomersgraphpotrex](https://user-images.githubusercontent.com/33809495/71517723-b3d9ba80-28af-11ea-8a72-110b2e7ecee7.png)

I am referring here to the **supporters** bar chart which indicates the amount of people that are installing the extension in a given time-frame. I believe that the graph is not very clear. In fact, it should be made explicit, on the X axis, to which month are we referring to. Moreover, as I show in the attached screenshot, when you over a specific bar it should indicate the date of reference and not just a number. For example, `20th December, 2019` instead of just `20`.

**Comment by vecna** [comment]
Thanks, there are few important revisions to be done in the _impact_ interface, I'll add your suggestion to the list.

**Comment by vecna** [comment]
reporting the full data might be difficult because of spacing, that's why I discourage to use the Month-Full-Name, but rather:

![image](https://user-images.githubusercontent.com/89555/71640808-82873300-2c91-11ea-9b21-aead954c9c20.png)

**Comment by vecna** [comment]
I think this is done now!
