### ISSUE TITLE
edit page potest/1

### ISSUE THREAD

**Issue by spaghettinucleari** [tracking-exposed/pornhub.tracking.exposed#15]
The page should include:
- [x] who we are and why we are doing this test
- [x] functioning and why it's a safe space
- [x] why you should join the experiment
- [x] download the browser extension
- [x] complete instructions about the data collection
- [x] deliverables

**Comment by vecna** [comment]
https://www.reddit.com/r/privacy/comments/equgcy/on_sunday_january_19th_2020_join_the_first/
