### ISSUE TITLE
precise amountGrossDimension

### ISSUE THREAD

**Issue by SalvatoreRomano1** [tracking-exposed/pornhub.tracking.exposed#21]
It would be nice to have the precise amountGrossDimension e.g:
- have seen 1 video on PH --> amountGrossDimension=1
- have seen 2 video on PH --> amountGrossDimension=2
- have seen 3 video on PH --> amountGrossDimension=3
...

**Comment by vecna** [comment]
should be solved now, it is reported the exact number of videos watched by the profile
