### ISSUE TITLE
Complete the 'compare' section 

### ISSUE THREAD

**Issue by spaghettinucleari** [tracking-exposed/pornhub.tracking.exposed#6]
http://bl.ocks.org/mthh/raw/7e17b680b35b83b49f1c22a3613bd89f/d698a37a435a017229b717ad3677899328d60edc/radarChart.js

**Comment by vecna** [comment]
Looks good?
![image](https://user-images.githubusercontent.com/89555/66214599-4c520b80-e6c2-11e9-8a1c-8c580c01ee26.png)

**Comment by spaghettinucleari** [comment]
![image](https://user-images.githubusercontent.com/47795057/66215107-2c6f1780-e6c3-11e9-8680-da1108b807a1.png)

**Comment by vecna** [comment]
Updated, now please provide meaningful texts 

![image](https://user-images.githubusercontent.com/89555/66219340-457bc680-e6cb-11e9-99e2-e3b34884de60.png)

**Comment by vecna** [comment]
TODO allow random users selection
